name: "Music Assistant (Custom Loader)"
description: "Music Assistant with custom plugin support. Coexists with official MA add-on."
url: "https://github.com/neqq3/ma_custom_loader"
version: "2.7.5"
slug: "ma-custom-loader"
ingress: false
arch:
  - aarch64
  - amd64
init: false
map:
  - "share:rw"
  - "media:rw"
options:
  log_level: "info"
schema:
  log_level: list(info|debug|warning|error|critical)
host_network: true
startup: application
boot: manual
hassio_role: manager
hassio_api: true
homeassistant_api: true
image: "ghcr.io/neqq3/ma-custom-loader-{arch}"
