name: "Music Assistant (Coexistence)"
description: "Music Assistant with custom plugin support. Designed to coexist with the official add-on."
url: "https://github.com/neqq3/ma_custom_loader"
version: "2.7.5"
slug: "ma-custom-loader-coexist"
ingress: true
ingress_port: 8093
arch:
  - aarch64
  - amd64
init: false
map:
  - "share:rw"
  - "media:rw"
options:
  log_level: "info"
schema:
  log_level: list(info|debug|warning|error|critical)
host_network: true
startup: application
boot: manual
hassio_role: manager
hassio_api: true
homeassistant_api: true
panel_icon: "mdi:music-box-multiple-outline"
panel_title: "Music Assistant (Coexist)"
panel_admin: false
image: "ghcr.io/neqq3/ma-custom-loader-coexist-{arch}"
