name: "Music Assistant (Customizable)"
description: "The music library manager of your dreams. Pre-loaded with NCloud Music + supports loading custom plugins from /share."
url: "https://github.com/music-assistant/server"
version: "2.0.0"
slug: "ma_custom_loader"
arch:
  - aarch64
  - amd64
init: false
map:
  - "share:rw"
  - "media:rw"
options:
  log_level: "info"
schema:
  log_level: "list(info, debug, warning, error, critical)"
ports:
  8095/tcp: 8095
webui: "http://[HOST]:[PORT:8095]"
host_network: true
startup: application
stage: experimental
panel_icon: "mdi:music-box-multiple"
image: "ghcr.io/neqq3/ma-custom-loader"
